### ISSUE TITLE
function Mouse.show_cursor(show=True) does not behave as expected

### ISSUE THREAD

**Issue by lindenloot** [open-cogsci/OpenSesame#729]
Version: 

- OpenSesame 3.3.5 Lentiform Loewenfeld 

Platforms tested: 

- Ubuntu 20.04.1 LTS
- Windows 10

Backends tested:

- Legacy
- PsychoPy
- PyGame

Issue:

When running the following code, the mouse cursor becomes visible only _after_ the click

```
my_canvas = Canvas()
my_mouse = Mouse()
my_mouse.show_cursor(show=True)
my_canvas.show()
button, (x, y), timestamp = my_mouse.get_click()
```

Replacing
```
my_mouse.show_cursor(show=True)
```

by 

```
my_mouse.visible = True
``` 

does result in the desired behavior (i.e. cursor visible before clicking).

**Comment by smathot** [comment]
This is actually the way it's supposed to work. `show_cursor()` changes the visibility immediately, whereas the `visible` property determines whether the cursor is visible during response collection. So what happens in this example is that the cursor is shown with `show_cursor()`, but then `get_click()` immediately undoes this because it relies on the `visible` property. This is not very clear in the documentation though, so I'll update that.
