### ISSUE TITLE
OpenSesame keeps giving me the same PermissionError

### ISSUE THREAD

**Issue by ghost** [open-cogsci/OpenSesame#778]
I've ran as administrator, moved OpenSesame to different folders, everything I can think of, which isn't much to be honest.

Here's the readout when I try to launch opensesame.bat:

C:\WINDOWS\system32>ECHO Please don't close this window. (Doing so will close OpenSesame.)
Please don't close this window. (Doing so will close OpenSesame.)

C:\WINDOWS\system32>cd /D C:\Program Files (x86)\OpenSesame\

C:\Program Files (x86)\OpenSesame>python.exe Lib\site-packages\opensesame.py
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files (x86)\OpenSesame\lib\multiprocessing\spawn.py", line 99, in spawn_main
    new_handle = reduction.steal_handle(parent_pid, pipe_handle)
  File "C:\Program Files (x86)\OpenSesame\lib\multiprocessing\reduction.py", line 87, in steal_handle
    _winapi.DUPLICATE_SAME_ACCESS | _winapi.DUPLICATE_CLOSE_SOURCE)
PermissionError: [WinError 5] Access is denied

Sorry if it's a bit of an inconvenience but I'm not extremely tech savvy, so any help given to me that's dumbed down would be much appreciated.

**Comment by smathot** [comment]
I suspect that this is a general issue with multiprocessing in Python on this system, and not something that is specific to OpenSesame (which is why I will close this issue here, because I want to limit the issue tracker to bugs in OpenSesame itself).

I'm guessing that this computer is a bit unusual in some way, perhaps very old or a university-managed system, and that OpenSesame runs fine on other computers. Is that correct?
