### ISSUE TITLE
Cannot post to Discussions forum (posted question to StackOverflow instead)

### ISSUE THREAD

**Issue by pablobernabeu** [open-cogsci/OpenSesame#785]
Hello,

I have signed up to the Discussions forum at https://forum.cogsci.nl/index.php?p=/discussions. Unfortunately, I cannot post a question. I wonder if it is because I haven't received the confirmation email. I have tried signing up with two different email addresses, and in neither case have I received the confirmation email (I've checked the spam folder). 

I would be very grateful for any help. In addition, I would be very grateful if someone could please consider the question I've posted at https://stackoverflow.com/questions/75869250/presenting-stimuli-from-two-loops-randomly-in-opensesame

Thank you very much

**Comment by smathot** [comment]
Hi Pablo,

You have a verified forum account associated with the University of Lancaster. I don't see any other accounts matching your name or email address (verified or otherwise), but if you let me know which account is yours I'll manually verify it so that you can log in. I guess the email must be blocked for some reason.

I'm afraid we don't answer questions through Stackoverflow, because we don't have the resources to maintain multiple platforms!

— Sebastiaan

**Comment by pablobernabeu** [comment]
Hi Sebastiaan,

Thank you very much. I understand. I'm no longer at Lancaster. The email
addresses I used to sign up over the last couple of days are from Gmail.
Could you please verify my account 'pbe', linked with ***@***.***?

**Comment by smathot** [comment]
Done!

**Comment by pablobernabeu** [comment]
Thank you!
