### ISSUE TITLE
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd

### ISSUE THREAD

**Issue by LenzWinkler** [open-cogsci/OpenSesame#786]
Starting PsychoPy in Windows (3.3.14-py37-win64-1\psychopy.bat) I get the following error message in the CMD window: `RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd`

The program starts anyway, but when I type "import psychopy" in the coder, I get the same error again: 

```
Python shell in PsychoPy (pid:16256) - type some commands!

Python 3.7.6 | packaged by conda-forge | (default, Jan  7 2020, 21:48:41) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import psychopy
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
>>> 
```

**Comment by smathot** [comment]
Thanks for reporting this! I'm closing the issue because it's a known (and harmless) side effect of an incompatibility that's specific to the windows packaging, rather than something to be fixed in the OpenSesame source code. You can ignore it for now, and the message will be gone in OpenSesame 4.0!
