### ISSUE TITLE
No macOS arm version since 3.3.10

### ISSUE THREAD

**Issue by suschizu** [open-cogsci/OpenSesame#792]
Will there be an arm-version for release 4.0.1?

**Comment by smathot** [comment]
There actually never was an M1/ ARM release for Mac OS. We did label it as such, but this was the result of a confusion on our side about the architecture. However, since a few months, Anaconda, which OpenSesame uses for the Python environment, provides Mac-OS-arm packages (they didn't do so before), which makes it feasible to build native OpenSesame packages for Mac OS ARM. However, this is a fairly low priority, and for now, you can safely use the Intel x64 packages for Mac OS. Alternatively, you can try to install a native environment yourself using Anaconda:

- https://osdoc.cogsci.nl/4.0/download/#anaconda-cross-platform

Hope this helps!

(I'm closing this issue because it's not related to an issue in OpenSesame as such.)

**Comment by suschizu** [comment]
great - thanks for the explanation!
