### ISSUE TITLE
Help with replicating an experiment using Opensesame

### ISSUE THREAD

**Issue by yanier-dalmau** [open-cogsci/OpenSesame#813]
A colleague asks me for help with this software.
She is studying an article in which the experiment was run using OpenSesame v3.0. We have the data from the experiment.
We have the latest version of the OpenSesame 4 series installed via PyPi, we also tried with version 3.3.14 but we cannot replicate the experiment using the data to study it.

First it asked us for dependencies like:
- fastnumber
- rusocsci
- One related to QT Engine (I don't remember the name)
All of the above solved

But the following stops us.

![image](https://github.com/user-attachments/assets/f2a72064-eeb3-4ebe-8db0-aeb76da8358d)

I understand that it seems that a connected USB device must be used and it fails when executing buttonbox.py. 

Is there a way to bypass this or simulate having the device with a standard keyboard?

**Comment by smathot** [comment]
Thanks for your interest in OpenSesame! I'm afraid this question should be directed at the person who created the task though. It seems like he or she wrote the experiment using a custom library for a buttonbox (not affiliated with OpenSesame), specifically this one: https://github.com/wilberth/RuSocSci

So I'm closing this issue. Not because I don't want to help you, but because the issue tracker is intended for bugs or enhancements to the OpenSesame source code itself, rather than user support. What I would do is either post the question on the [support forum](https://forum.cogsci.nl) and hope that someone familiar with this buttonbox will reply (also attach the actual experiment!), or contact the original developer of the experiment.
